### ISSUE TITLE
Keyboard flicker

### ISSUE THREAD

**Issue by admmasters** [driftyco/ionic-plugins-keyboard#80]
Still occurs when using CrossWalk.

**Comment by admmasters** [comment]
Open keyboard on Android and there is a flicker.

**Comment by tlancina** [comment]
If you remove the keyboard plugin does the flicker go away?

**Comment by mattchue** [comment]
Just following up because I was playing around with this plugin this morning. I tested with the plugin installed, and without it installed and I still get a keyboard flicker.

**Comment by tlancina** [comment]
Yeah I'm pretty sure it doesn't have to do with the plugin, considering the plugin is just passively listening for layout changes and doesn't actually do anything to the view layout. Thanks for the follow up @mattchue! Let us know if you figure out how to get rid of it, since it seems to be a common issue.
